version: '2'

networks:
  app-tier:
    driver: bridge

services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=$USER
      - MINIO_ROOT_PASSWORD=$PASSWORD
      - MINIO_SERVER_ACCESS_KEY=$KEY
      - MINIO_SERVER_SECRET_KEY=$KEY
    volumes:
      - ./.minio:/root/.minio
      - minio_storage:/data
    networks:
      - app-tier

volumes:
  minio_storage: {}
